name: Go

on:
  push:
    branches: [master]

env:
  REPOSITORY_NAME: SaniGistUploader

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: |
          gcloud auth activate-service-account --key-file "$GOOGLE_APPLICATION_CREDENTIALS"
          git config --global credential.'https://source.developers.google.com'.helper gcloud.sh

      - name: Add remote and push
        run: |
          git remote add google https://source.developers.google.com/p/${{ secrets.GCP_PROJECT_ID }}/r/$REPOSITORY_NAME
          git push --all google
